ergonode_transformer_api:
    resource: '../../Application/Controller/Api/Transformer*'
    type: annotation
    prefix: /api/v1/

ergonode_processor_api:
    resource: '../../Application/Controller/Api/Processor*'
    type: annotation
    prefix: /api/v1/
